apiVersion: v2
name: yc-keda-external-scaler
description: KEDA external scaler for Yandex Monitoring
type: application
version: 1.1.3
appVersion: "v1.2.19"
maintainers:
  - name: Kirill Shevchuk
    email: kirshe@yandex-team.ru
    url: https://github.com/knpsh
